spring:
  application:
    name: erp
  # spring datasource configuration ???
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password:
    url: 'jdbc:h2:mem:erp'  # H2 ? JDBC URL, mem???????, erp???????
  h2:
    console:
      enabled: true  # ????? H2 ? console ?????????? table
      path: '/h2' # ??? console ? URL ??
  jpa:
    hibernate:
      ddl-auto: update  # ? spring boot entity ????, ????? DB scheam
    database-platform: org.hibernate.dialect.H2Dialect