---- User
CREATE TABLE ERP_USER(
       USERID INT PRIMARY KEY,
       USERNAME VARCHAR(50), PASSWORD VARCHAR(50),
       EMPLOYEEID INT,
       ROLEID INT,
       LASTLOGINTIME TIMESTAMP NOT NULL,
       STATUS VARCHAR(50)
);



-- User
INSERT INTO ERP_USER (USERID, USERNAME, PASSWORD, EMPLOYEEID, ROLEID, LASTLOGINTIME, STATUS)
VALUES(1, '吳泓儒', '123456', 1, 1, TIMESTAMP'2025-04-14T15:16:17', 'AVAILABLE' );